=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module OpenapiClient
  class CorporateType
    N101 = 101.freeze
    N201 = 201.freeze
    N301 = 301.freeze
    N302 = 302.freeze
    N303 = 303.freeze
    N304 = 304.freeze
    N305 = 305.freeze
    N399 = 399.freeze
    N401 = 401.freeze
    N499 = 499.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = CorporateType.constants.select { |c| CorporateType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #CorporateType" if constantValues.empty?
      value
    end
  end
end
