=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module OpenapiClient
  class Prefecture
     = "北海道".freeze
     = "青森県".freeze
     = "岩手県".freeze
     = "宮城県".freeze
     = "秋田県".freeze
     = "山形県".freeze
     = "福島県".freeze
     = "茨城県".freeze
     = "栃木県".freeze
     = "群馬県".freeze
     = "埼玉県".freeze
     = "千葉県".freeze
     = "東京都".freeze
     = "神奈川県".freeze
     = "新潟県".freeze
     = "富山県".freeze
     = "石川県".freeze
     = "福井県".freeze
     = "山梨県".freeze
     = "長野県".freeze
     = "岐阜県".freeze
     = "静岡県".freeze
     = "愛知県".freeze
     = "三重県".freeze
     = "滋賀県".freeze
     = "京都府".freeze
     = "大阪府".freeze
     = "兵庫県".freeze
     = "奈良県".freeze
     = "和歌山県".freeze
     = "鳥取県".freeze
     = "島根県".freeze
     = "岡山県".freeze
     = "広島県".freeze
     = "山口県".freeze
     = "徳島県".freeze
     = "香川県".freeze
     = "愛媛県".freeze
     = "高知県".freeze
     = "福岡県".freeze
     = "佐賀県".freeze
     = "長崎県".freeze
     = "熊本県".freeze
     = "大分県".freeze
     = "宮崎県".freeze
     = "鹿児島県".freeze
     = "沖縄県".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Prefecture.constants.select { |c| Prefecture::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #Prefecture" if constantValues.empty?
      value
    end
  end
end
