=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module OpenapiClient
  class ProcessCode
    N01 = "01".freeze
    N11 = "11".freeze
    N12 = "12".freeze
    N13 = "13".freeze
    N21 = "21".freeze
    N22 = "22".freeze
    N71 = "71".freeze
    N72 = "72".freeze
    N81 = "81".freeze
    N99 = "99".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ProcessCode.constants.select { |c| ProcessCode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ProcessCode" if constantValues.empty?
      value
    end
  end
end
