=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CnsOpenapiRubyClient::CorporateType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CnsOpenapiRubyClient::CorporateType do
  let(:instance) { CnsOpenapiRubyClient::CorporateType.new }

  describe 'test an instance of CorporateType' do
    it 'should create an instance of CorporateType' do
      expect(instance).to be_instance_of(CnsOpenapiRubyClient::CorporateType)
    end
  end
end
