=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CnsOpenapiRubyClient::ProcessCodeType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CnsOpenapiRubyClient::ProcessCodeType do
  let(:instance) { CnsOpenapiRubyClient::ProcessCodeType.new }

  describe 'test an instance of ProcessCodeType' do
    it 'should create an instance of ProcessCodeType' do
      expect(instance).to be_instance_of(CnsOpenapiRubyClient::ProcessCodeType)
    end
  end
end
