=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

module CnsOpenapiRubyClient
  VERSION = '1.0.3'
end
