=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CorporationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CorporationApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CorporationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CorporationApi' do
    it 'should create an instance of CorporationApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CorporationApi)
    end
  end

  # unit tests for get_users_user_id
  # Your GET endpoint
  # get corporations
  # @param name corporation name
  # @param type response format type
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :mode search mode
  # @option opts [Float] :target search target JIS level
  # @option opts [Float] :address prefecture code or, prefecture &amp; city code
  # @option opts [Float] :kind corporation type
  # @option opts [Float] :change change history enable or disable
  # @option opts [Float] :close close corporation enable or disable
  # @option opts [String] :from corporation number start date
  # @option opts [String] :to corporation number end date
  # @option opts [Float] :divide division number
  # @return [Array<Corporation>]
  describe 'get_users_user_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
