=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CorrectCode
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CorrectCode do
  let(:instance) { OpenapiClient::CorrectCode.new }

  describe 'test an instance of CorrectCode' do
    it 'should create an instance of CorrectCode' do
      expect(instance).to be_instance_of(OpenapiClient::CorrectCode)
    end
  end
end
