=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::Error400
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::Error400 do
  let(:instance) { OpenapiClient::Error400.new }

  describe 'test an instance of Error400' do
    it 'should create an instance of Error400' do
      expect(instance).to be_instance_of(OpenapiClient::Error400)
    end
  end
  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["010", "011", "012", "013", "020", "021", "022", "030", "031", "040", "041", "042", "043", "050", "051", "052", "060", "061", "062", "063", "070", "071", "072", "073", "080", "081", "082", "090", "100", "101", "102", "103", "110", "111", "112", "120", "121", "122", "130", "131", "132", "140", "141", "142", "150", "151", "152", "160", "161", "170", "180"])
      # validator.allowable_values.each do |value|
      #   expect { instance.code = value }.not_to raise_error
      # end
    end
  end

end
