=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::Prefecture
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::Prefecture do
  let(:instance) { OpenapiClient::Prefecture.new }

  describe 'test an instance of Prefecture' do
    it 'should create an instance of Prefecture' do
      expect(instance).to be_instance_of(OpenapiClient::Prefecture)
    end
  end
end
