=begin
#Corporate number system API v4

#Corporate number system API v4

The version of the OpenAPI document: 1.0.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

# Common files
require 'cns_openapi_ruby_client/api_client'
require 'cns_openapi_ruby_client/api_error'
require 'cns_openapi_ruby_client/version'
require 'cns_openapi_ruby_client/configuration'

# Models
require 'cns_openapi_ruby_client/models/corporate_type'
require 'cns_openapi_ruby_client/models/corporation'
require 'cns_openapi_ruby_client/models/correct_code_type'
require 'cns_openapi_ruby_client/models/process_code_type'
require 'cns_openapi_ruby_client/models/response'
require 'cns_openapi_ruby_client/models/response_wrapper'

# APIs
require 'cns_openapi_ruby_client/api/corporations_api'

module CnsOpenapiRubyClient
  class << self
    # Customize default settings for the SDK using block.
    #   CnsOpenapiRubyClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
